var s_iOffsetX=0,s_iOffsetY=0,s_fInverseScaling=0;
(function(c){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(c)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(c.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(c){console.log(c)}function isIOS(){for(var c="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");c.length;)if(navigator.platform===c.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(c){var d=c.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+c])c=e["client"+c];else if(window["inner"+c]!=e["client"+c]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var a=b.createElement("div");a.id="vpw-test-d";a.style.cssText="position:absolute;top:-1000px";a.innerHTML="<style>@media("+d+":"+e["client"+c]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(a);e.insertBefore(g,b.head);
c=7==a["offset"+c]?e["client"+c]:window["inner"+c];e.removeChild(g)}else c=window["inner"+c];return c}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var c=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<c?c:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var c;c=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");s_iScaleFactor=Math.min(c/CANVAS_HEIGHT,d/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,g;e<c?(g=c-e,e+=g,b+=CANVAS_WIDTH/CANVAS_HEIGHT*g):b<d&&(g=d-b,b+=g,e+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=c/2-e/2;var a=d/2-b/2,k=CANVAS_WIDTH/b;if(a*k<-EDGEBOARD_X||g*k<-EDGEBOARD_Y)s_iScaleFactor=Math.min(c/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,e=CANVAS_HEIGHT*s_iScaleFactor,g=(c-e)/2,a=(d-b)/2,k=CANVAS_WIDTH/b;s_fInverseScaling=k;s_iOffsetX=-1*a*k;s_iOffsetY=-1*g*k;0<=g&&(s_iOffsetY=0);0<=a&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile&&!s_bIsIphone?($("#canvas").css("width",b+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=
b,s_oStage.canvas.height=e,s_oStage.scaleX=s_oStage.scaleY=Math.min(b/CANVAS_WIDTH,e/CANVAS_HEIGHT));0>g?($("#canvas").css("top",g+"px"),s_iCanvasOffsetHeight=g):($("#canvas").css("top","0px"),s_iCanvasOffsetHeight=0);$("#canvas").css("left",a+"px");s_iCanvasResizeWidth=b;s_iCanvasResizeHeight=e;s_iCanvasOffsetWidth=a}}
function createBitmap(c,d,b){var e=new createjs.Bitmap(c),g=new createjs.Shape;d&&b?g.graphics.beginFill("#fff").drawRect(-d/2,-b/2,d,b):g.graphics.beginFill("#ff0").drawRect(0,0,c.width,c.height);e.hitArea=g;return e}function createSprite(c,d,b,e,g,a){c=null!==d?new createjs.Sprite(c,d):new createjs.Sprite(c);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-e,g,a);c.hitArea=d;return c}function roundDecimal(c,d){var b=Math.pow(10,d);return Math.round(b*c)/b}
function randomFloatBetween(c,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(c+Math.random()*(d-c),d).toFixed(b))}function shuffle(c){for(var d=c.length,b,e;0!==d;)e=Math.floor(Math.random()*d),--d,b=c[d],c[d]=c[e],c[e]=b;return c}function formatTime(c){c/=1E3;var d=Math.floor(c/60);c=parseFloat(c-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return 10>c?b+("0"+c):b+c}function degreesToRadians(c){return c*Math.PI/180}
function checkRectCollision(c,d){var b,e;b=getBounds(c,.9);e=getBounds(d,.98);return calculateIntersection(b,e)}function calculateIntersection(c,d){var b,e,g,a,k,l,f,q;b=c.x+(g=c.width/2);e=c.y+(a=c.height/2);k=d.x+(l=d.width/2);f=d.y+(q=d.height/2);b=Math.abs(b-k)-(g+l);e=Math.abs(e-f)-(a+q);return 0>b&&0>e?(b=Math.min(Math.min(c.width,d.width),-b),e=Math.min(Math.min(c.height,d.height),-e),{x:Math.max(c.x,d.x),y:Math.max(c.y,d.y),width:b,height:e,rect1:c,rect2:d}):null}
function getBounds(c,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(c instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=c.children,g=e.length,a,k;for(k=0;k<g;k++)a=getBounds(e[k],1),a.x<b.x&&(b.x=a.x),a.y<b.y&&(b.y=a.y),a.x+a.width>b.x2&&(b.x2=a.x+a.width),a.y+a.height>b.y2&&(b.y2=a.y+a.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var l,f;c instanceof createjs.Bitmap?
(g=c.sourceRect||c.image,k=g.width*d,l=g.height*d):c instanceof createjs.Sprite?c.spriteSheet._frames&&c.spriteSheet._frames[c.currentFrame]&&c.spriteSheet._frames[c.currentFrame].image?(g=c.spriteSheet.getFrame(c.currentFrame),k=g.rect.width,l=g.rect.height,e=g.regX,f=g.regY):(b.x=c.x||0,b.y=c.y||0):(b.x=c.x||0,b.y=c.y||0);e=e||0;k=k||0;f=f||0;l=l||0;b.regX=e;b.regY=f;g=c.localToGlobal(0-e,0-f);a=c.localToGlobal(k-e,l-f);k=c.localToGlobal(k-e,0-f);e=c.localToGlobal(0-e,l-f);b.x=Math.min(Math.min(Math.min(g.x,
a.x),k.x),e.x);b.y=Math.min(Math.min(Math.min(g.y,a.y),k.y),e.y);b.width=Math.max(Math.max(Math.max(g.x,a.x),k.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,a.y),k.y),e.y)-b.y}return b}function NoClickDelay(c){this.element=c;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(c){switch(c.type){case "touchstart":this.onTouchStart(c);break;case "touchmove":this.onTouchMove(c);break;case "touchend":this.onTouchEnd(c)}},onTouchStart:function(c){c.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(c){this.moved=!0},onTouchEnd:function(c){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){c=document.elementFromPoint(c.changedTouches[0].clientX,c.changedTouches[0].clientY);3==c.nodeType&&(c=c.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);c.dispatchEvent(d)}}};
(function(){function c(c){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};c=c||window.event;c.type in e?document.body.className=e[c.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",c):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",c):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",c):(d="msHidden")in document?document.addEventListener("msvisibilitychange",c):"onfocusin"in document?document.onfocusin=document.onfocusout=c:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=c})();function playSound(c,d,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(c,{loop:b,volume:d}):null}function stopSound(c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.stop()}
function setVolume(c,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.volume=d}function setMute(c,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||c.setMute(d)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(c){for(var d=window.location.search.substring(1).split("&"),b=0;b<d.length;b++){var e=d[b].split("=");if(e[0]==c)return e[1]}}
function CSpriteLibrary(){var c,d,b,e,g,a;this.init=function(k,l,f){b=d=0;e=k;g=l;a=f;c={}};this.addSprite=function(a,g){c.hasOwnProperty(a)||(c[a]={szPath:g,oSprite:new Image},d++)};this.getSprite=function(a){return c.hasOwnProperty(a)?c[a].oSprite:null};this._onSpritesLoaded=function(){g.call(a)};this._onSpriteLoaded=function(){e.call(a);++b===d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in c)c[a].oSprite.oSpriteLibrary=this,c[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
c[a].oSprite.onerror=function(){s_oMain.onImageLoadError($(this).attr("src"))},c[a].oSprite.src=c[a].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=768,EDGEBOARD_X=90,EDGEBOARD_Y=95,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_COME_OUT=1,STATE_GAME_COME_POINT=2,ON_SHOW_BET_ON_TABLE=0,ON_SHOW_ENLIGHT=1,ON_HIDE_ENLIGHT=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CONTROLLER_END=6,ON_CONTROLLER_REMOVE=7,ON_CONTROLLER_ROLL=8,TOTAL_MONEY,NUM_FICHES=6,MIN_BET,MAX_BET,
WIN_OCCURRENCE,TIME_FICHES_MOV=1500,TIME_SHOW_DICES_RESULT,NUM_DICE_ROLLING_FRAMES=34,NUM_BALL_SPIN_FRAMES=200,NUM_HAND_FOR_ADS,FONT1="arialbold",FONT2="Digital-7";
function CGameSettings(){var c,d,b,e;this._init=function(){this._initAttachFiches();this._initBetMultiplier();this._setPuckPos();c=[1,5,10,25,50,100];NUM_FICHES=c.length};this._initAttachFiches=function(){e=[];e.pass_line={x:360,y:555};e.dont_pass1={x:730,y:503};e.dont_pass2={x:254,y:320};e.dont_come={x:322,y:238};e.come={x:740,y:330};e.field={x:570,y:420};e.big_6={x:260,y:440};e.big_8={x:316,y:490};for(var g=[{value:4,x:408,y:142},{value:5,x:494,y:142},{value:6,x:580,y:142},{value:8,x:666,y:142},
{value:9,x:752,y:142},{value:10,x:838,y:142}],a=0;a<g.length;a++)e["lay_bet"+g[a].value]={x:g[a].x+20,y:g[a].y},e["lose_bet"+g[a].value]={x:g[a].x-20,y:g[a].y+20},e["number"+g[a].value]={x:g[a].x,y:g[a].y+69},e["win_bet"+g[a].value]={x:g[a].x,y:g[a].y+116};e.any11_7={x:1032,y:582};e.any_craps_7={x:1032,y:631};e.seven_bet={x:1032,y:356};e.hardway6={x:955,y:400};e.hardway10={x:1112,y:400};e.hardway8={x:955,y:460};e.hardway4={x:1112,y:460};e.horn3={x:930,y:520};e.horn2={x:1032,y:520};e.horn12={x:1134,
y:520};e.oDealerWin={x:CANVAS_WIDTH/2,y:-232};e.oReceiveWin={x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT+100}};this._initBetMultiplier=function(){d=[];d.pass_line=1;d.dont_pass1=1;d.dont_pass2=1;d.dont_come=1;d.come=1;d.field=1;d.big_6=1;d.big_8=1;for(var g=[4,5,6,8,9,10],a=[.5,.66,.83,.83,.66,.5],c=[.45,.62,.8,.8,.62,.45],b=[2,1.5,1.2,1.2,1.5,2],f=[1.8,1.4,1.17,1.17,1.4,1.8],e=0;e<g.length;e++)d["lay_bet"+g[e]]=a[e],d["lose_bet"+g[e]]=c[e],d["number"+g[e]]=b[e],d["win_bet"+g[e]]=f[e];d.any11_7=15;d.any_craps_7=
7;d.seven_bet=4;d.hardway6=9;d.hardway10=7;d.hardway8=9;d.hardway4=7;d.horn3=15;d.horn2=30;d.horn12=30};this.generateFichesPileByIndex=function(g){var a=[],k,b=c.length-1,f=c[b];do{k=g%f;k=roundDecimal(k,1);g=roundDecimal(g/f,1);g=Math.floor(g);for(var e=0;e<g;e++)a.push(this.getFicheIndexByValue(f));b--;f=c[b];g=k}while(0<k&&-1<b);return a};this._setPuckPos=function(){b=[];b[4]=410;b[5]=495;b[6]=580;b[8]=666;b[9]=752;b[10]=836};this.getBetWinLoss=function(g,a,c){var b=[0,0,0,0,0,0,0,0,0,0,0,0],f=
[0,0,0,0,0,0,0,0,0,0,0,0];switch(c){case "pass_line":g===STATE_GAME_COME_OUT?(b[6]=1,b[10]=1,f[1]=1,f[2]=1,f[11]=1):(b[a-1]=1,f[6]=1);break;case "come":b[6]=1;b[10]=1;f[1]=1;f[2]=1;f[11]=1;break;case "dont_pass1":case "dont_pass2":g===STATE_GAME_COME_OUT?(b[1]=1,b[2]=1,b[11]=1,f[6]=1,f[10]=1):(b[6]=1,f[a-1]=1);break;case "dont_come":b[1]=1;b[2]=1;b[11]=1;f[6]=1;f[10]=1;break;case "field":b[1]=1;b[2]=1;b[3]=1;b[8]=1;b[9]=1;b[10]=1;b[11]=1;f[0]=1;f[4]=1;f[5]=1;f[6]=1;f[7]=1;break;case "big_6":b[5]=
1;break;case "big_8":b[7]=1;break;case "lay_bet4":case "lose_bet4":b[6]=1;f[3]=1;break;case "lay_bet5":case "lose_bet5":b[6]=1;f[4]=1;break;case "lay_bet6":case "lose_bet6":b[6]=1;f[5]=1;break;case "lay_bet8":case "lose_bet8":b[6]=1;f[7]=1;break;case "lay_bet9":case "lose_bet9":b[6]=1;f[8]=1;break;case "lay_bet10":case "lose_bet10":b[6]=1;f[9]=1;break;case "number4":case "win_bet4":b[3]=1;f[6]=1;break;case "number5":case "win_bet5":b[4]=1;f[6]=1;break;case "number6":case "win_bet6":b[5]=1;f[6]=1;
break;case "number8":case "win_bet8":b[7]=1;f[6]=1;break;case "number9":case "win_bet9":b[8]=1;f[6]=1;break;case "number10":case "win_bet10":b[9]=1;f[6]=1;break;case "any11":b[10]=1;f[1]=1;f[2]=1;f[3]=1;f[4]=1;f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[11]=1;break;case "any_craps":b[1]=1;b[2]=1;b[11]=1;f[3]=1;f[4]=1;f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;break;case "seven_bet":b[6]=1;f[1]=1;f[2]=1;f[3]=1;f[4]=1;f[5]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "hardway6":b[5]=1;f[1]=1;f[2]=1;f[3]=
1;f[4]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "hardway10":b[9]=1;f[1]=1;f[2]=1;f[3]=1;f[4]=1;f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[10]=1;f[11]=1;break;case "hardway8":b[7]=1;f[1]=1;f[2]=1;f[3]=1;f[4]=1;f[5]=1;f[6]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "hardway4":b[3]=1;f[1]=1;f[2]=1;f[3]=1;f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "horn3":b[2]=1;f[1]=1;f[3]=1;f[4]=1;f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "horn2":b[1]=1;f[2]=1;f[3]=1;f[4]=1;
f[5]=1;f[6]=1;f[7]=1;f[8]=1;f[9]=1;f[10]=1;f[11]=1;break;case "horn12":b[11]=1,f[1]=1,f[2]=1,f[3]=1,f[4]=1,f[5]=1,f[6]=1,f[7]=1,f[8]=1,f[9]=1,f[10]=1}return{win:b,lose:f}};this.checkBetWin=function(b,a,c,e,f,d){var h=-1;switch(f){case "pass_line":if(a===STATE_GAME_COME_OUT)if(2===b||3===b||12===b)h=0;else{if(7===b||11===b)h=c*s_oGameSettings.getBetMultiplier(f)}else 7===b?h=0:b===e&&(h=c*s_oGameSettings.getBetMultiplier(f));break;case "come":7===b||11===b?h=c*s_oGameSettings.getBetMultiplier(f):2===
b||3===b||12===b?h=0:s_oGame.assignBetFromCome(b,f);break;case "dont_pass1":case "dont_pass2":a===STATE_GAME_COME_OUT?2===b||3===b?h=c*s_oGameSettings.getBetMultiplier(f):7===b||11===b?h=0:12===b&&(h=c):7===b?h=c*s_oGameSettings.getBetMultiplier(f):b===e&&(h=0);break;case "dont_come":2===b||7===b?h=c*s_oGameSettings.getBetMultiplier(f):7===b||11===b?h=0:s_oGame.assignBetFromDontCome(b,f);break;case "field":if(5===b||6===b||7===b||8===b)trace("field lose"),h=0;else if(trace("field win"),h=c*s_oGameSettings.getBetMultiplier(f),
2===b||12===b)h*=2;break;case "big_6":6===b?(trace("big6 win"),h=c*s_oGameSettings.getBetMultiplier(f)):7===b&&(h=0);break;case "big_8":8===b?(trace("big8 win"),h=c*s_oGameSettings.getBetMultiplier(f)):7===b&&(h=0);break;case "lay_bet4":case "lose_bet4":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),"lay_bet4"===f&&(h=roundDecimal(.05*h,2))):4===b&&(h=0);break;case "lay_bet5":case "lose_bet5":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),"lay_bet5"===f&&(h=roundDecimal(.05*h,2))):5===b&&(h=0);break;
case "lay_bet6":case "lose_bet6":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),"lay_bet6"===f&&(h=roundDecimal(.05*h,2))):6===b&&(h=0);break;case "lay_bet8":case "lose_bet8":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),"lay_bet8"===f&&(h=roundDecimal(.05*h,2))):8===b&&(h=0);break;case "lay_bet9":case "lose_bet9":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),"lay_bet9"===f&&(h=roundDecimal(.05*h,2))):9===b&&(h=0);break;case "lay_bet10":case "lose_bet10":7===b?(h=c*s_oGameSettings.getBetMultiplier(f),
"lay_bet10"===f&&(h=roundDecimal(.05*h,2))):10===b&&(h=0);break;case "number4":case "win_bet4":a===STATE_GAME_COME_POINT&&(4===b?(h=c*s_oGameSettings.getBetMultiplier(f),"number4"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "number5":case "win_bet5":a===STATE_GAME_COME_POINT&&(5===b?(h=c*s_oGameSettings.getBetMultiplier(f),"number5"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "number6":case "win_bet6":a===STATE_GAME_COME_POINT&&(6===b?(h=c*s_oGameSettings.getBetMultiplier(f),
"number6"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "number8":case "win_bet8":a===STATE_GAME_COME_POINT&&(8===b?(h=c*s_oGameSettings.getBetMultiplier(f),"number8"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "number9":case "win_bet9":a===STATE_GAME_COME_POINT&&(9===b?(h=c*s_oGameSettings.getBetMultiplier(f),"number9"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "number10":case "win_bet10":a===STATE_GAME_COME_POINT&&(10===b?(h=c*s_oGameSettings.getBetMultiplier(f),
"number10"===f&&(h=roundDecimal(.05*c,2))):7===b&&(h=0));break;case "any11_7":h=11===b?c*s_oGameSettings.getBetMultiplier(f):0;break;case "any_craps_7":h=2===b||3===b||12===b?c*s_oGameSettings.getBetMultiplier(f):0;break;case "seven_bet":h=7===b?c*s_oGameSettings.getBetMultiplier(f):0;break;case "hardway6":h=3===d[0]&&3===d[1]?c*s_oGameSettings.getBetMultiplier(f):0;break;case "hardway10":h=5===d[0]&&5===d[1]?c*s_oGameSettings.getBetMultiplier(f):0;break;case "hardway8":h=4===d[0]&&4===d[1]?c*s_oGameSettings.getBetMultiplier(f):
0;break;case "hardway4":h=2===d[0]&&2===d[1]?c*s_oGameSettings.getBetMultiplier(f):0;break;case "horn3":h=3===b?c*s_oGameSettings.getBetMultiplier(f):0;break;case "horn2":h=2===b?c*s_oGameSettings.getBetMultiplier(f):0;break;case "horn12":h=12===b?c*s_oGameSettings.getBetMultiplier(f):0}return h};this.getFicheValues=function(b){return c[b]};this.getFicheIndexByValue=function(b){for(var a=0,e=0;e<c.length;e++)if(b===c[e]){a=e;break}return a};this.getBetMultiplier=function(b){return d[b]};this.getAttachOffset=
function(b){return e[b]};this.getHelpMsgByBet=function(b){return(void 0)[b]};this.getPuckXByNumber=function(c){return b[c]};this._init()}
function CFichesController(c){var d,b,e,g;this._init=function(a){g=a;this.reset()};this.reset=function(){this._removeAllFichesOnTable();d=[];b=[];e=[]};this.setFicheOnTable=function(a,b,c){-1!==b.indexOf("any_craps_")?b="any_craps_7":-1!==b.indexOf("any11_")&&(b="any11_7");this.addFicheOnTable(a,b,c)};this.addFicheOnTable=function(a,c,e){void 0===d[c]&&(d[c]=0);a=s_oGameSettings.getFicheValues(a);d[c]+=a;d[c]=roundDecimal(d[c],1);a=s_oGameSettings.generateFichesPileByIndex(d[c]);a.sort(function(a,
b){return a-b});this._removeFichesPile(b[c]);b[c]=[];for(var f=s_oGameSettings.getAttachOffset(c),g=f.x,f=f.y,h=0;h<a.length;h++)e.push(this._attachFichesPile(a[h],c,g,f)),f-=5};this._attachFichesPile=function(a,c,d,f){a=new CFiche(d,f,a,g);b[c].push(a);e.push(a);return a};this._removeAllFichesOnTable=function(){if(e)for(var a=0;a<e.length;a++)g.contains(e[a].getSprite())&&g.removeChild(e[a].getSprite())};this._removeFichesPile=function(a){for(var b in a)g.removeChild(a[b].getSprite())};this.removeBet=
function(a){b[a]=[];d[a]=0};this.swapBet=function(a,c){b[c]=b[a];d[c]=d[a];this.removeBet(a)};this.clearAllBets=function(){this._removeAllFichesOnTable();d=[];b=[];e=[]};this.clearAllBetsInComePoint=function(){if(b){var a=0,c;for(c in b)if("pass_line"!==c&&"dont_pass1"!==c&&"dont_pass2"!==c){for(var a=a+d[c],l=0;l<b[c].length;l++)g.removeChild(b[c][l].getSprite());delete d[c];delete b[c];delete e[c]}}return a};this.getFicheMc=function(a){return b[a]};this.getBetAmountInPos=function(a){return d[a]};
this._init(c)}
var TEXT_MONEY="MONEY",TEXT_CUR_BET="CUR BET",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",TEXT_ROLL="ROLL",TEXT_EXIT="EXIT",TEXT_RECHARGE="RECHARGE",TEXT_YOU_WIN="GREAT!! YOU WIN",TEXT_CURRENCY="$",TEXT_ARE_SURE="ARE YOU SURE?",TEXT_COME_OUT="COME OUT",TEXT_ERROR_NO_MONEY_MSG="NOT ENOUGH MONEY FOR THIS BET!!",TEXT_ERROR_MAX_BET_REACHED="MAX BET REACHED!!",TEXT_ERROR_MIN_BET="YOU BET IS LOWER THAN MINIMUM BET!!",TEXT_NO_MONEY="YOU DON'T HAVE ENOUGH MONEY!!!",TEXT_RECHARGE_MSG="PLEASE CLICK RECHARGE BUTTON TO PLAY AGAIN",TEXT_WAITING_BET=
"WAITING FOR YOUR BET...",TEXT_READY_TO_ROLL="ROLL WHEN YOU'RE READY!",TEXT_HELP_MSG=[];TEXT_HELP_MSG.pass_line="PLACE YOUR BET ON PASS LINE";TEXT_HELP_MSG.dont_pass1="PLACE YOUR BET ON DON'T PASS";TEXT_HELP_MSG.dont_pass2="PLACE YOUR BET ON DON'T PASS";TEXT_HELP_MSG.dont_come="PLACE YOUR BET ON DON'T COME";TEXT_HELP_MSG.come="PLACE YOUR BET ON COME";TEXT_HELP_MSG.field="PLACE YOUR BET ON FIELD";TEXT_HELP_MSG.big_6="PLACE YOUR BET ON BIG 6";TEXT_HELP_MSG.big_8="PLACE YOUR BET ON BIG 8";
for(var aValues=[4,5,6,8,9,10],aInfosLay="1:2 ON 7 BEFORE POINT LESS 5% OF WIN;2:3 ON 7 BEFORE POINT LESS 5% OF WIN;5:6 ON 7 BEFORE POINT LESS 5% OF WIN;5:6 ON 7 BEFORE POINT LESS 5% OF WIN;2:3 ON 7 BEFORE POINT LESS 5% OF WIN;1:2 ON 7 BEFORE POINT LESS 5% OF WIN".split(";"),aInfosLose="5:11 ON 7 BEFORE POINT;5:8 ON 7 BEFORE POINT;4:5 ON 7 BEFORE POINT;4:5 ON 7 BEFORE POINT;5:8 ON 7 BEFORE POINT;5:11 ON 7 BEFORE POINT".split(";"),aInfosBuy="2:1 ON MAKING POINT LESS 5% OF BET;3:2 ON MAKING POINT LESS 5% OF BET;6:5 ON MAKING POINT LESS 5% OF BET;6:5 ON MAKING POINT LESS 5% OF BET;3:2 ON MAKING POINT LESS 5% OF BET;2:1 ON MAKING POINT LESS 5% OF BET".split(";"),
aInfosWin="9:5 ON MAKING POINT;7:5 ON MAKING POINT;7:6 ON MAKING POINT;7:6 ON MAKING POINT;7:5 ON MAKING POINT;9:5 ON MAKING POINT".split(";"),i=0;i<aValues.length;i++)TEXT_HELP_MSG["lay_bet"+aValues[i]]="PLACE YOUR BET ON LAY "+aValues[i]+" - "+aInfosLay[i],TEXT_HELP_MSG["lose_bet"+aValues[i]]="PLACE YOUR BET ON LOSE "+aValues[i]+" - "+aInfosLose[i],TEXT_HELP_MSG["number"+aValues[i]]="PLACE YOUR BET ON BUY "+aValues[i]+" - "+aInfosBuy[i],TEXT_HELP_MSG["win_bet"+aValues[i]]="PLACE YOUR BET ON WIN "+
aValues[i]+" - "+aInfosWin[i];for(var j=0;8>j;j++)TEXT_HELP_MSG["any11_"+j]="PLACE YOUR BET ON HORN 11",TEXT_HELP_MSG["any_craps_"+j]="PLACE YOUR BET ON ANY CRAPS";TEXT_HELP_MSG.seven_bet="PLACE YOUR BET ON ANY 7";TEXT_HELP_MSG.hardway6="PLACE YOUR BET ON HARDWAY 6";TEXT_HELP_MSG.hardway10="PLACE YOUR BET ON HARDWAY 10";TEXT_HELP_MSG.hardway8="PLACE YOUR BET ON HARDWAY 8";TEXT_HELP_MSG.hardway4="PLACE YOUR BET ON HARDWAY 4";TEXT_HELP_MSG.horn3="PLACE YOUR BET ON HORN 3";TEXT_HELP_MSG.horn2="PLACE YOUR BET ON HORN 2";
TEXT_HELP_MSG.horn12="PLACE YOUR BET ON HORN 12";var TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_LINK="WWW.CODETHISLAB.COM",TEXT_CONGRATULATIONS="Congratulations!",TEXT_SHARE_1="You collected <strong>",TEXT_SHARE_2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_3="My score is ",TEXT_SHARE_4=" points! Can you do better?";
function CPreloader(){var c,d,b,e,g,a;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();a=new createjs.Container;s_oStage.addChild(a)};this.unload=function(){a.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));a.addChild(k);e=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));e.x=400;e.y=CANVAS_HEIGHT-140;a.addChild(e);c=476;g=new createjs.Shape;g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(400,CANVAS_HEIGHT-140,1,30);a.addChild(g);e.mask=g;d=new createjs.Text("0%","30px "+FONT1,"#fff");d.x=450;d.y=CANVAS_HEIGHT-140;d.textAlign="center";d.textBaseline="middle";a.addChild(d);b=new createjs.Text("0%","30px "+
FONT2,"#fff");b.x=CANVAS_WIDTH+200;b.y=CANVAS_HEIGHT+140;b.textAlign="center";b.textBaseline="middle";a.addChild(b)};this.refreshLoader=function(a){d.text=a+"%";b.text=a+"%";a=Math.floor(a*c/100);g.graphics.clear();g.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(400,CANVAS_HEIGHT-140,a,30)};this._init()}
function CMain(c){var d,b=0,e=0,g=STATE_LOADING,a,k,l;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(FPS);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};
this.soundLoaded=function(){b++;b===e&&(k.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/chip.ogg","chip"),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/fiche_collect.ogg",
"fiche_collect"),createjs.Sound.registerSound("./sounds/fiche_select.ogg","fiche_select"),createjs.Sound.registerSound("./sounds/dice_rolling.ogg","dice_rolling"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/lose.ogg","lose")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/chip.mp3","chip"),createjs.Sound.registerSound("./sounds/click.mp3",
"click"),createjs.Sound.registerSound("./sounds/fiche_collect.mp3","fiche_collect"),createjs.Sound.registerSound("./sounds/fiche_select.mp3","fiche_select"),createjs.Sound.registerSound("./sounds/dice_rolling.mp3","dice_rolling"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/lose.mp3","lose")),e+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("chip_box","./sprites/chip_box.png");s_oSpriteLibrary.addSprite("but_bets","./sprites/but_bets.png");s_oSpriteLibrary.addSprite("but_bg","./sprites/but_bg.png");s_oSpriteLibrary.addSprite("but_clear_all","./sprites/but_clear_all.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");
s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("enlight_any_craps","./sprites/enlight_any_craps.png");s_oSpriteLibrary.addSprite("enlight_big_6","./sprites/enlight_big_6.png");s_oSpriteLibrary.addSprite("enlight_big_8","./sprites/enlight_big_8.png");s_oSpriteLibrary.addSprite("enlight_circle","./sprites/enlight_circle.png");
s_oSpriteLibrary.addSprite("enlight_come","./sprites/enlight_come.png");s_oSpriteLibrary.addSprite("enlight_dont_come","./sprites/enlight_dont_come.png");s_oSpriteLibrary.addSprite("enlight_dont_pass1","./sprites/enlight_dont_pass1.png");s_oSpriteLibrary.addSprite("enlight_dont_pass2","./sprites/enlight_dont_pass2.png");s_oSpriteLibrary.addSprite("enlight_field","./sprites/enlight_field.png");s_oSpriteLibrary.addSprite("enlight_lay_bet","./sprites/enlight_lay_bet.png");s_oSpriteLibrary.addSprite("enlight_lose_bet",
"./sprites/enlight_lose_bet.png");s_oSpriteLibrary.addSprite("enlight_number","./sprites/enlight_number.png");s_oSpriteLibrary.addSprite("enlight_pass_line","./sprites/enlight_pass_line.png");s_oSpriteLibrary.addSprite("enlight_proposition1","./sprites/enlight_proposition1.png");s_oSpriteLibrary.addSprite("enlight_proposition2","./sprites/enlight_proposition2.png");s_oSpriteLibrary.addSprite("enlight_seven","./sprites/enlight_seven.png");s_oSpriteLibrary.addSprite("enlight_any11","./sprites/enlight_any11.png");
s_oSpriteLibrary.addSprite("hit_area_any_craps","./sprites/hit_area_any_craps.png");s_oSpriteLibrary.addSprite("hit_area_big_8","./sprites/hit_area_big_8.png");s_oSpriteLibrary.addSprite("hit_area_big_6","./sprites/hit_area_big_6.png");s_oSpriteLibrary.addSprite("hit_area_circle","./sprites/hit_area_circle.png");s_oSpriteLibrary.addSprite("hit_area_come","./sprites/hit_area_come.png");s_oSpriteLibrary.addSprite("hit_area_dont_come","./sprites/hit_area_dont_come.png");s_oSpriteLibrary.addSprite("hit_area_dont_pass1",
"./sprites/hit_area_dont_pass1.png");s_oSpriteLibrary.addSprite("hit_area_dont_pass2","./sprites/hit_area_dont_pass2.png");s_oSpriteLibrary.addSprite("hit_area_field","./sprites/hit_area_field.png");s_oSpriteLibrary.addSprite("hit_area_lay_bet","./sprites/hit_area_lay_bet.png");s_oSpriteLibrary.addSprite("hit_area_lose_bet","./sprites/hit_area_lose_bet.png");s_oSpriteLibrary.addSprite("hit_area_number","./sprites/hit_area_number.png");s_oSpriteLibrary.addSprite("hit_area_pass_line","./sprites/hit_area_pass_line.png");
s_oSpriteLibrary.addSprite("hit_area_proposition1","./sprites/hit_area_proposition1.png");s_oSpriteLibrary.addSprite("hit_area_proposition2","./sprites/hit_area_proposition2.png");s_oSpriteLibrary.addSprite("hit_area_seven","./sprites/hit_area_seven.png");s_oSpriteLibrary.addSprite("hit_area_any11","./sprites/hit_area_any11.png");s_oSpriteLibrary.addSprite("select_fiche","./sprites/select_fiche.png");s_oSpriteLibrary.addSprite("roll_but","./sprites/roll_but.png");s_oSpriteLibrary.addSprite("dices_screen_bg",
"./sprites/dices_screen_bg.jpg");s_oSpriteLibrary.addSprite("logo_game_0","./sprites/logo_game_0.png");s_oSpriteLibrary.addSprite("board_table","./sprites/board_table.jpg");s_oSpriteLibrary.addSprite("display_bg","./sprites/display_bg.png");s_oSpriteLibrary.addSprite("puck","./sprites/puck.png");s_oSpriteLibrary.addSprite("dice_topdown1","./sprites/dice_topdown1.png");s_oSpriteLibrary.addSprite("dice_topdown2","./sprites/dice_topdown2.png");s_oSpriteLibrary.addSprite("but_not","./sprites/but_not.png");
s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("dice_a","./sprites/dice_a.png");s_oSpriteLibrary.addSprite("dice_b","./sprites/dice_b.png");s_oSpriteLibrary.addSprite("dices_box","./sprites/dices_box.png");for(var a=0;a<NUM_FICHES;a++)s_oSpriteLibrary.addSprite("fiche_"+a,"./sprites/fiche_"+a+".png");for(a=0;a<NUM_DICE_ROLLING_FRAMES;a++)s_oSpriteLibrary.addSprite("launch_dices_"+a,"./sprites/launch_dice_anim/launch_dices_"+a+".png");e+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/e*100));b===e&&(k.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.onImageLoadError=function(a){};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(){l=new CGame(a);g=STATE_GAME};this.gotoHelp=
function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&l.update();
s_oStage.update(a)}};s_oMain=this;a=c;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary;
function CTextButton(c,d,b,e,g,a,k,l){var f,q,h,m,r,v,t,p,w,n;this._init=function(a,b,c,e,d,g,k,l){f=!1;m=[];r=[];n=createBitmap(c);q=c.width;h=c.height;var v=Math.ceil(k/20);p=new createjs.Text(e,k+"px "+d,"#000000");var B=p.getBounds();p.textAlign="center";p.textBaseline="alphabetic";p.x=c.width/2+v;p.y=Math.floor(c.height/2)+B.height/3+v;w=new createjs.Text(e,k+"px "+d,g);w.textAlign="center";w.textBaseline="alphabetic";w.x=c.width/2;w.y=Math.floor(c.height/2)+B.height/3;t=new createjs.Container;
t.x=a;t.y=b;t.regX=c.width/2;t.regY=c.height/2;s_bMobile||(t.cursor="pointer");t.addChild(n,p,w);!1!==l&&s_oStage.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown");t.off("pressup");s_oStage.removeChild(t)};this.setVisible=function(a){t.visible=a};this.setAlign=function(a){w.textAlign=a;p.textAlign=a};this.enable=function(){f=!1;n.filters=[];n.cache(0,0,q,h)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(0);n.filters=
[new createjs.ColorMatrixFilter(a)];n.cache(0,0,q,h)};this._initListener=function(){t.on("mousedown",this.buttonDown);t.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){m[a]=b;r[a]=c};this.addEventListenerWithParams=function(a,b,c,f){m[a]=b;r[a]=c;v=f};this.buttonRelease=function(){f||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click"),t.scaleX=1,t.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(r[ON_MOUSE_UP],v))};this.buttonDown=function(){f||(t.scaleX=.9,
t.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){t.x=a;t.y=b};this.changeText=function(a){w.text=a;p.text=a};this.setX=function(a){t.x=a};this.setY=function(a){t.y=a};this.getX=function(){return t.x};this.getY=function(){return t.y};this.getSprite=function(){return t};this._init(c,d,b,e,g,a,k,l);return this}
function CGfxButton(c,d,b,e){var g,a,k,l,f,q,h,m;this._init=function(b,c,e){g=!1;l=[];f=[];h=createBitmap(e);a=e.width;k=e.height;h.x=b;h.y=c;h.regX=e.width/2;h.regY=e.height/2;s_bMobile||(h.cursor="pointer");m.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);!1===s_bMobile&&(h.off("rollover",this.mouseOver),h.off("rollout",this.mouseOut));m.removeChild(h)};this.setVisible=function(a){h.visible=a};this.enable=function(){g=
!1;h.filters=[];h.cache(0,0,a,k)};this.disable=function(){g=!0;var b=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);h.filters=[new createjs.ColorMatrixFilter(b)];h.cache(0,0,a,k)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease);!1===s_bMobile&&(h.on("rollover",this.mouseOver),h.on("rollout",this.mouseOut))};this.addEventListener=function(a,b,c){l[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,e){l[a]=b;f[a]=c;
q=e};this.buttonRelease=function(){g||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click"),h.scaleX=1,h.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(f[ON_MOUSE_UP],q))};this.buttonDown=function(){g||(h.scaleX=.9,h.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],q))};this.mouseOver=function(){l[ON_MOUSE_OVER]&&l[ON_MOUSE_OVER].call(f[ON_MOUSE_OVER],q)};this.mouseOut=function(){l[ON_MOUSE_OUT]&&l[ON_MOUSE_OUT].call(f[ON_MOUSE_OUT],q)};this.setPosition=function(a,
b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getX=function(){return h.x};this.getY=function(){return h.y};m=e;this._init(c,d,b);return this}
function CFicheBut(c,d,b){var e,g,a,k,l,f,q=[],h,m,r;this._init=function(b,c,d){g=!1;m=new createjs.Container;s_oStage.addChild(m);e=!1;l=[];f=[];h=createBitmap(d);h.x=b;h.y=c;h.regX=d.width/2;h.regY=d.height/2;s_bMobile||(h.cursor="pointer");m.addChild(h);a=d.width;k=d.height;d=s_oSpriteLibrary.getSprite("select_fiche");r=createBitmap(d);r.x=b-2;r.y=c-2;r.regX=d.width/2;r.regY=d.height/2;m.addChild(r);r.visible=e;this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",
this.buttonRelease);s_oStage.removeChild(m)};this.select=function(){e=!0;r.visible=e};this.deselect=function(){e=!1;r.visible=e};this.enable=function(){g=!1;h.filters=[];h.cache(0,0,a,k)};this.disable=function(){g=!0;var b=(new createjs.ColorMatrix).adjustSaturation(-90);h.filters=[new createjs.ColorMatrixFilter(b)];h.cache(0,0,a,k)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,c){l[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,b,c,e){l[a]=b;f[a]=c;q=e};this.buttonRelease=function(){g||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click"),h.scaleX=1,h.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(f[ON_MOUSE_UP],q),e=!e,r.visible=e)};this.buttonDown=function(){g||(h.scaleX=.9,h.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],q))};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=
a};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(c,d,b)}
function CBetTableButton(c,d,b,e,g){var a,k,l,f,q;this._init=function(b,c,e,d,g){f=d;a=[];k=[];q=g;l=new createjs.Bitmap(e);l.x=b;l.y=c;l.regX=e.width/2;l.regY=e.height/2;s_bMobile||(l.cursor="pointer");this._initListener();q.addChild(l)};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);l.off("rollover",this.mouseOver);l.off("rollout",this.mouseOut);q.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){l.on("mousedown",
this.buttonDown);l.on("pressup",this.buttonRelease);l.on("rollover",this.mouseOver);l.on("rollout",this.mouseOut)};this.addEventListener=function(b,c,f){a[b]=c;k[b]=f};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");a[ON_MOUSE_UP]&&a[ON_MOUSE_UP].call(k[ON_MOUSE_UP],{button:f},!1)};this.buttonDown=function(){a[ON_MOUSE_DOWN]&&a[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],{button:f},!1)};this.mouseOver=function(){a[ON_MOUSE_OVER]&&a[ON_MOUSE_OVER].call(k[ON_MOUSE_OVER],
{enlight:f})};this.mouseOut=function(){a[ON_MOUSE_OUT]&&a[ON_MOUSE_OUT].call(k[ON_MOUSE_OUT],{enlight:f})};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(c,d,b,e,g)}
function CToggle(c,d,b){var e,g,a;this._init=function(b,c,f){e=[];g=[];var d=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{on:[0,1],off:[1,2]}});a=s_bAudioActive?createSprite(d,"on",f.width/2/2,f.height/2,f.width/2,f.height):createSprite(d,"off",f.width/2/2,f.height/2,f.width/2,f.height);a.x=b;a.y=c;a.stop();s_bMobile||(a.cursor="pointer");s_oStage.addChild(a);this._initListener()};this.unload=function(){a.off("mousedown",
this.buttonDown);a.off("pressup",this.buttonRelease);s_oStage.removeChild(a)};this._initListener=function(){a.on("mousedown",this.buttonDown);a.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;g[a]=c};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");a.scaleX=1;a.scaleY=1;(s_bAudioActive=!s_bAudioActive)?a.gotoAndStop("on"):a.gotoAndStop("off");e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){a.scaleX=
.9;a.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(b,c){a.x=b;a.y=c};this._init(c,d,b)}
function CMenu(){var c,d,b,e,g,a,k,l,f,q,h;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);var m=s_oSpriteLibrary.getSprite("but_play");b=CANVAS_WIDTH/2;e=CANVAS_HEIGHT-110;l=new CGfxButton(b,e,m,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);m=s_oSpriteLibrary.getSprite("but_credits");c=CANVAS_WIDTH-m.height/2-10;d=m.height/2+10;f=new CGfxButton(c,d,m,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onCredits,this);if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),g=c-m.width/2-10,a=m.height/2+10,q=new CToggle(g,a,m),q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},400).call(function(){h.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(h,k){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(g-h,k+a);
f.setPosition(c-h,k+d);l.setPosition(b,e-k)};this.unload=function(){l.unload();l=null;f.unload();f=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;s_oStage.removeChild(k);k=null;s_oStage.removeChild(h);s_oMenu=h=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._onCredits=function(){new CCreditsPanel};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(c){var d=!1,b,e,g,a,k,l,f,q,h,m,r,v,t,p,w,n,u,x,y,z,A;this._init=function(){s_oTweenController=new CTweenController;s_oGameSettings=new CGameSettings;x=new CTableController;x.addEventListener(ON_SHOW_ENLIGHT,this._onShowEnlight);x.addEventListener(ON_HIDE_ENLIGHT,this._onHideEnlight);x.addEventListener(ON_SHOW_BET_ON_TABLE,this._onShowBetOnTable);b=!1;q=0;a=e=-1;v={};p=new CSeat;n=new CPuck(325,108,s_oStage);u=new CInterface;w=new CDicesAnim(240,159);A=new CAreYouSurePanel(s_oStage);
z=new CGameOver;y=new CMsgBox;h=[];g=0;this._onSitDown();d=!0};this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.stop();u.unload();x.unload();y.unload();z.unload();s_oStage.removeAllChildren()};this._setState=function(b){e=b;switch(b){case STATE_GAME_WAITING_FOR_BET:if(p.getCredit()<s_oGameSettings.getFicheValues(0)){e=-1;setTimeout(function(){u.hideBlock();z.show()},2E3);return}a=-1;k=0;l=Math.floor(3*Math.random()+3);u.enableClearButton();0===p.getCurBet()&&u.enableRoll(!1);
q++;q>NUM_HAND_FOR_ADS&&(q=0,$(s_oMain).trigger("show_interlevel_ad"));u.hideBlock()}x.setState(b)};this._prepareForRolling=function(){u.disableBetFiches();u.disableClearButton();k++;m=[];this._generateWinLoss();h.push(m);g=0};this._generateWinLoss=function(){var b;b=f<2*p.getCurBet()?0:WIN_OCCURRENCE;var c,d,g;for(g in v)-1!==g.indexOf("any11_")?g="any11":-1!==g.indexOf("any_craps")&&(g="any_craps"),d=s_oGameSettings.getBetWinLoss(e,a,g),c=d.lose,d=d.win;if(Math.floor(100*Math.random())>=b)if(k>
l){do b=this._generateRandomDices(),g=b[0]+b[1];while(0===c[g-1])}else{do b=this._generateRandomDices(),g=b[0]+b[1],g=0===d[g-1]?!0:!1;while(!g)}else if(k>l)if(-1!==g.indexOf("hardway"))b=this._checkHardwayWin(g);else{do b=this._generateRandomDices(),g=b[0]+b[1];while(0===d[g-1])}else if(-1!==g.indexOf("hardway"))b=this._checkHardwayWin(g);else{do b=this._generateRandomDices(),g=b[0]+b[1],g=0===c[g-1]?!1:!0;while(g)}m[0]=b[0];m[1]=b[1]};this._generateRandomDices=function(){var a=[],b=Math.floor(6*
Math.random())+1;a.push(b);b=Math.floor(6*Math.random())+1;a.push(b);return a};this._checkHardwayWin=function(a){var b=6,c=6;switch(a){case "hardway6":c=b=3;break;case "hardway10":c=b=5;break;case "hardway8":c=b=4;break;case "hardway4":c=b=2}do a=this._generateRandomDices();while(a[0]!==b||a[1]!==c);return a};this._checkIfLosingResult=function(a,b){return 0===b[a[0]+a[1]-1]?!1:!0};this._startRollingAnim=function(){w.startRolling(m)};this.dicesAnimEnded=function(){var c=m[0]+m[1];if(e===STATE_GAME_COME_OUT){2!==
c&&3!==c&&12!==c&&7!==c&&11!==c&&this._assignNumber(c);this._checkWinForBet();if(0<r.length){b=!0;for(var f=0;f<t.length;f++)p.removeBet(t[f]),delete v[t[f]];u.setCurBet(p.getCurBet())}-1!==a&&this._setState(STATE_GAME_COME_POINT)}else{this._checkWinForBet();if(0<r.length){b=!0;for(f=0;f<t.length;f++)p.removeBet(t[f]),delete v[t[f]];u.setCurBet(p.getCurBet())}a===c?(n.switchOff(),this._setState(STATE_GAME_WAITING_FOR_BET)):7===c&&(n.switchOff(),this._setState(STATE_GAME_WAITING_FOR_BET))}u.setMoney(p.getCredit());
0<Object.keys(v).length&&(u.enableRoll(!0),u.enableClearButton());u.hideBlock();u.enableBetFiches();$(s_oMain).trigger("save_score",[p.getCredit()])};this._assignNumber=function(b){a=b;b=s_oGameSettings.getPuckXByNumber(a);n.switchOn(b);u.hideBlock()};this._checkWinForBet=function(){var b=m[0]+m[1],c=0;r=[];t=[];for(var d in v){var g=d;-1!==d.indexOf("any11_")?d="any11_7":-1!==d.indexOf("any_craps")&&(d="any_craps_7");var h=p.getBetAmountInPos(g),h=s_oGameSettings.checkBetWin(b,e,h,a,d,m);if(-1!==
h){var c=c+h,k=p.getFicheMc(d);t.push(g);for(var l=0;l<k.length;l++){r.push(k[l]);if(0<h){var n=s_oGameSettings.getAttachOffset("oReceiveWin");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win",{volume:.2})}else n=s_oGameSettings.getAttachOffset("oDealerWin"),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("lose",{volume:.2});k[l].setEndPoint(n.x,n.y);p.decreaseBet(s_oGameSettings.getFicheValues(r[l].getValue()))}0<h&&(p.showWin(p.getBetAmountInPos(g)+h),f-=h,g=k[0].getStartingPos(),
new CScoreText(h+TEXT_CURRENCY,g.x,g.y))}}0<c&&(u.refreshMsgHelp(TEXT_YOU_WIN+": "+c),setTimeout(function(){u.clearMsgHelp()},3E3))};this.assignBetFromCome=function(a,b){for(var c=p.getFicheMc(b),f=0;f<c.length;f++){r.push(c[f]);var d=s_oGameSettings.getAttachOffset("number"+a);c[f].setEndPoint(d.x,d.y)}v["number"+a]=v[b];delete v[b];p.swapBet(b,"number"+a)};this.assignBetFromDontCome=function(a,b){for(var c=p.getFicheMc(b),f=0;f<c.length;f++){r.push(c[f]);var d=s_oGameSettings.getAttachOffset("lay_bet"+
a);c[f].setEndPoint(d.x,d.y)}v["lay_bet"+a]=v[b];delete v[b];p.swapBet(b,"lay_bet"+a)};this.onRecharge=function(){p.recharge(TOTAL_MONEY);u.setMoney(p.getCredit());this._setState(STATE_GAME_WAITING_FOR_BET);z.hide();$(s_oMain).trigger("recharge")};this.onRoll=function(){0!==p.getCurBet()&&(p.getCurBet()<MIN_BET?(y.show(TEXT_ERROR_MIN_BET),u.enableBetFiches(),u.enableRoll(!0)):u.isBlockVisible()||(u.showBlock(),e===STATE_GAME_WAITING_FOR_BET&&this._setState(STATE_GAME_COME_OUT),this._prepareForRolling(),
this._startRollingAnim()))};this._onSitDown=function(){this._setState(STATE_GAME_WAITING_FOR_BET);p.setInfo(TOTAL_MONEY,x.getContainer());u.setMoney(TOTAL_MONEY);u.setCurBet(0)};this._onShowBetOnTable=function(a){var b=a.button,c=u.getCurFicheSelected(),f=s_oGameSettings.getFicheValues(c),d=p.getCurBet();0>p.getCredit()-f?y.show(TEXT_ERROR_NO_MONEY_MSG):d+f>MAX_BET?y.show(TEXT_ERROR_MAX_BET_REACHED):(v[a.button]=void 0===v[a.button]?f:v[a.button]+f,p.addFicheOnTable(f,c,b),u.setMoney(p.getCredit()),
u.setCurBet(p.getCurBet()),u.enableRoll(!0),u.refreshMsgHelp(TEXT_READY_TO_ROLL,!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("chip"))};this._onShowEnlight=function(a){if(a=a.enlight)x.enlight(a),u.refreshMsgHelp(TEXT_HELP_MSG[a],!1)};this._onHideEnlight=function(a){if(a=a.enlight)x.enlightOff(a),u.clearMsgHelp()};this.onClearAllBets=function(){if(e===STATE_GAME_COME_POINT){p.clearAllBetsInComePoint();for(var a in v)"pass_line"!==a&&"dont_pass1"!==a&&"dont_pass2"!==a&&delete v[a]}else p.clearAllBets(),
v={},u.enableRoll(!1);u.setMoney(p.getCredit());u.setCurBet(p.getCurBet())};this.onExit=function(a){a?(this.unload(),s_oMain.gotoMenu()):A.show()};this.onConfirmExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",p.getCredit())};this._updateDistributeFiches=function(){g+=s_iTimeElaps;if(g>TIME_FICHES_MOV)g=0,b=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("fiche_collect");else for(var a=s_oTweenController.easeInOutCubic(g,
0,1,TIME_FICHES_MOV),c=0;c<r.length;c++)r[c].updatePos(a)};this.update=function(){!1!==d&&(b&&this._updateDistributeFiches(),w.isVisible()&&w.update())};s_oGame=this;TOTAL_MONEY=c.money;MIN_BET=c.min_bet;MAX_BET=c.max_bet;WIN_OCCURRENCE=c.win_occurrence;TIME_SHOW_DICES_RESULT=c.time_show_dice_result;NUM_HAND_FOR_ADS=c.num_hand_before_ads;f=c.casino_cash;this._init()}var s_oGame,s_oTweenController,s_oGameSettings;
function CInterface(){var c,d,b,e,g,a,k,l,f,q,h,m,r,v,t,p,w;this._init=function(){var n=createBitmap(s_oSpriteLibrary.getSprite("but_bg"));n.x=251;n.y=603;s_oStage.addChild(n);n=new createjs.Text(TEXT_MONEY,"16px "+FONT1,"#fff");n.textAlign="center";n.textBaseline="alphabetic";n.x=332;n.y=629;s_oStage.addChild(n);q=new createjs.Text("","16px "+FONT1,"#fff");q.textAlign="center";q.textBaseline="alphabetic";q.x=332;q.y=649;s_oStage.addChild(q);n=createBitmap(s_oSpriteLibrary.getSprite("but_bg"));n.x=
410;n.y=603;s_oStage.addChild(n);n=new createjs.Text(TEXT_CUR_BET,"16px "+FONT1,"#fff");n.textAlign="center";n.textBaseline="alphabetic";n.x=492;n.y=629;s_oStage.addChild(n);h=new createjs.Text("","16px "+FONT1,"#fff");h.textAlign="center";h.textBaseline="alphabetic";h.x=492;h.y=649;s_oStage.addChild(h);v=createBitmap(s_oSpriteLibrary.getSprite("but_bets"));v.x=575;v.y=610;s_oStage.addChild(v);m=new createjs.Text(TEXT_MIN_BET+": "+MIN_BET+"\n"+TEXT_MAX_BET+": "+MAX_BET,"16px "+FONT1,"#fff");m.textAlign=
"center";m.textBaseline="alphabetic";m.lineHeight=21;m.x=v.x+75;m.y=v.y+19;s_oStage.addChild(m);n=createBitmap(s_oSpriteLibrary.getSprite("display_bg"));n.x=880;n.y=210;s_oStage.addChild(n);r=new createjs.Text(TEXT_WAITING_BET,"20px "+FONT2,"#ffde00");r.textAlign="center";r.lineWidth=140;r.lineHeight=20;r.x=n.x+175;r.y=n.y+13;s_oStage.addChild(r);a=TEXT_WAITING_BET;t=new CTextButton(1030,162,s_oSpriteLibrary.getSprite("roll_but"),"  "+TEXT_ROLL,FONT1,"#fff",22,s_oStage);t.disable();t.setAlign("left");
t.addEventListener(ON_MOUSE_UP,this._onRoll,this);p=new CGfxButton(764,636,s_oSpriteLibrary.getSprite("but_clear_all"),s_oStage);p.addEventListener(ON_MOUSE_UP,this._onClearAllBet,this);this._initFichesBut();g=0;k[g].select();n=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);w=new createjs.Shape(n);w.on("click",function(){});w.visible=!1;s_oStage.addChild(w);n=s_oSpriteLibrary.getSprite("but_exit");c=CANVAS_WIDTH-n.width/2-10;d=n.height/2+10;l=new CGfxButton(c,
d,n,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),b=c-n.width/2-10,e=n.height/2+10,f=new CToggle(b,e,n),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.unload();t.unload();p.unload();s_oInterface=null};this.refreshButtonPos=function(a,g){!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||f.setPosition(b-a,e+g);l.setPosition(c-a,d+g)};this.hideBlock=function(){w.visible=!1};this.showBlock=function(){w.visible=!0};this.enableBetFiches=function(){for(var a=0;a<NUM_FICHES;a++)k[a].enable()};this.enableClearButton=function(){p.enable()};this.disableBetFiches=function(){for(var a=0;a<NUM_FICHES;a++)k[a].disable()};this.disableClearButton=function(){p.disable()};this.deselectAllFiches=function(){for(var a=0;a<NUM_FICHES;a++)k[a].deselect()};this.enableRoll=function(a){a?
t.enable():t.disable()};this._initFichesBut=function(){var a=createBitmap(s_oSpriteLibrary.getSprite("chip_box"));a.x=82;a.y=94;s_oStage.addChild(a);a=144;k=[];for(var b=0;b<NUM_FICHES;b++){var c=s_oSpriteLibrary.getSprite("fiche_"+b);k[b]=new CFicheBut(124,a,c);k[b].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheSelected,this,[b]);a+=c.height+25}};this.setMoney=function(a){q.text=a.toFixed(2)+TEXT_CURRENCY};this.refreshMoney=function(a,b){new CRollingTextController(q,null,a,parseFloat(b),4E3,
EASE_LINEAR,TEXT_CURRENCY)};this.setCurBet=function(a){h.text=a.toFixed(2)+TEXT_CURRENCY};this.refreshMsgHelp=function(b,c){r.text=b;c&&(a=b)};this.clearMsgHelp=function(){r.text=a};this._onBetRelease=function(a){null!==a.numbers&&s_oGame._onShowBetOnTable({button:a.name},!1)};this._onFicheSelected=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("fiche_select");this.deselectAllFiches();a=a[0];for(var b=0;b<NUM_FICHES;b++)b===a&&(g=b)};this._onRoll=function(){this.disableBetFiches();
this.enableRoll(!1);s_oGame.onRoll()};this._onClearAllBet=function(){s_oGame.onClearAllBets()};this._onExit=function(){s_oGame.onExit(!1)};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this.getCurFicheSelected=function(){return g};this.isBlockVisible=function(){return w.visible};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CMsgBox(){var c,d,b,e;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.on("click",function(){});b=new createjs.Text("","24px "+FONT1,"#000");b.x=CANVAS_WIDTH/2+2;b.y=CANVAS_HEIGHT/2-28;b.textAlign="center";b.lineWidth=300;d=new createjs.Text("","24px "+FONT1,"#ffffff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-30;d.textAlign="center";d.lineWidth=300;e=new createjs.Container;e.alpha=0;e.visible=!1;e.addChild(c,b,d);s_oStage.addChild(e)};this.unload=function(){c.off("click",
function(){})};this.show=function(c){b.text=c;d.text=c;e.alpha=0;e.visible=!0;var a=this;createjs.Tween.get(e).to({alpha:1},500);setTimeout(function(){a._onExit()},2E3)};this._onExit=function(){e.visible&&(e.visible=!1)};this._init();return this}
function CTweenController(){this.tweenValue=function(c,d,b){return c+b*(d-c)};this.easeLinear=function(c,d,b,e){return b*c/e+d};this.easeInCubic=function(c,d,b,e){e=(c/=e)*c*c;return d+b*e};this.easeBackInQuart=function(c,d,b,e){e=(c/=e)*c;return d+b*(2*e*e+2*e*c+-3*e)};this.easeInBack=function(c,d,b,e){return b*(c/=e)*c*(2.70158*c-1.70158)+d};this.easeOutCubic=function(c,d,b,e){return b*((c=c/e-1)*c*c+1)+d};this.easeInOutCubic=function(c,d,b,e){return 1>(c/=e/2)?b/2*c*c*c+d:b/2*((c-=2)*c*c+2)+d};
this.tweenVectors=function(c,d,b,e){e.x=c.x+b*(d.x-c.x);e.y=c.y+b*(d.y-c.y);return e}}
function CSeat(){var c,d,b,e;this._init=function(){this.reset()};this.reset=function(){b=[];e&&e.reset();c=0};this.setInfo=function(b,a){d=b;c=0;e=new CFichesController(a)};this.setFicheBetted=function(b,a,e){c+=b*e;d-=b*e;d=roundDecimal(d,1)};this.addFicheOnTable=function(b,a,c){var d=[];e.setFicheOnTable(a,c,d);this.setFicheBetted(b,d,1)};this.decreaseBet=function(b){c-=b};this.removeBet=function(b){e.removeBet(b)};this.swapBet=function(b,a){e.swapBet(b,a)};this.clearAllBets=function(){e.clearAllBets();
d+=c;d=roundDecimal(d,1);c=0};this.clearAllBetsInComePoint=function(){var b=e.clearAllBetsInComePoint();c-=b;d+=b;d=roundDecimal(d,1)};this.showWin=function(b){d+=b;d=roundDecimal(d,1)};this.recharge=function(b){d=b};this.getCurBet=function(){return c};this.getCredit=function(){return d};this.getNumberSelected=function(){return b};this.getFicheMc=function(b){return e.getFicheMc(b)};this.getBetAmountInPos=function(b){return e.getBetAmountInPos(b)};this._init()}
function CTableController(){var c,d,b,e,g;this._init=function(){b=new createjs.Container;s_oStage.addChild(b);var a=createBitmap(s_oSpriteLibrary.getSprite("board_table"));b.addChild(a);this._initEnlights();this._initButtonBets();this.setState(STATE_GAME_WAITING_FOR_BET);e=[];g=[]};this._initEnlights=function(){var a;d=[];a=new CEnlight(175,162,s_oSpriteLibrary.getSprite("enlight_pass_line"),b);d.pass_line=a;a=new CEnlight(365,476,s_oSpriteLibrary.getSprite("enlight_dont_pass1"),b);d.dont_pass1=a;
a=new CEnlight(227,127,s_oSpriteLibrary.getSprite("enlight_dont_pass2"),b);d.dont_pass2=a;a=new CEnlight(279,127,s_oSpriteLibrary.getSprite("enlight_dont_come"),b);d.dont_come=a;a=new CEnlight(279,264,s_oSpriteLibrary.getSprite("enlight_come"),b);d.come=a;for(var c=[{value:4,x:365,y:127},{value:5,x:451,y:127},{value:6,x:537,y:127},{value:8,x:623,y:127},{value:9,x:709,y:127},{value:10,x:795,y:127}],e=0;6>e;e++)a=new CEnlight(c[e].x,c[e].y,s_oSpriteLibrary.getSprite("enlight_lay_bet"),b),d["lay_bet"+
c[e].value]=a,a=new CEnlight(c[e].x,c[e].y+30,s_oSpriteLibrary.getSprite("enlight_lose_bet"),b),d["lose_bet"+c[e].value]=a,a=new CEnlight(c[e].x,c[e].y+41,s_oSpriteLibrary.getSprite("enlight_number"),b),d["number"+c[e].value]=a,a=new CEnlight(c[e].x,c[e].y+125,s_oSpriteLibrary.getSprite("enlight_lose_bet"),b),d["win_bet"+c[e].value]=a;a=new CEnlight(226,391,s_oSpriteLibrary.getSprite("enlight_big_6"),b);d.big_6=a;a=new CEnlight(240,434,s_oSpriteLibrary.getSprite("enlight_big_8"),b);d.big_8=a;a=new CEnlight(281,
391,s_oSpriteLibrary.getSprite("enlight_field"),b);d.field=a;for(var c=401,f=409,e=0;7>e;e++)a=new CEnlight(806,c,s_oSpriteLibrary.getSprite("enlight_circle"),b),d["any11_"+e]=a,a=new CEnlight(840,f,s_oSpriteLibrary.getSprite("enlight_circle"),b),d["any_craps_"+e]=a,c+=37,f+=34;a=new CEnlight(877,551,s_oSpriteLibrary.getSprite("enlight_any11"),b);d["any11_"+e]=a;a=new CEnlight(877,612,s_oSpriteLibrary.getSprite("enlight_any_craps"),b);d["any_craps_"+e]=a;a=new CEnlight(877,371,s_oSpriteLibrary.getSprite("enlight_proposition1"),
b);d.hardway6=a;a=new CEnlight(1032,371,s_oSpriteLibrary.getSprite("enlight_proposition1"),b);d.hardway10=a;a=new CEnlight(877,431,s_oSpriteLibrary.getSprite("enlight_proposition1"),b);d.hardway8=a;a=new CEnlight(1032,431,s_oSpriteLibrary.getSprite("enlight_proposition1"),b);d.hardway4=a;a=new CEnlight(877,491,s_oSpriteLibrary.getSprite("enlight_proposition2"),b);d.horn3=a;a=new CEnlight(980,491,s_oSpriteLibrary.getSprite("enlight_proposition2"),b);d.horn2=a;a=new CEnlight(1083,491,s_oSpriteLibrary.getSprite("enlight_proposition2"),
b);d.horn12=a;a=new CEnlight(877,338,s_oSpriteLibrary.getSprite("enlight_seven"),b);d.seven_bet=a};this._initButtonBets=function(){c=[];var a;a=new CBetTableButton(485,371,s_oSpriteLibrary.getSprite("hit_area_pass_line"),"pass_line",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.pass_line=a;a=new CBetTableButton(580,501,s_oSpriteLibrary.getSprite("hit_area_dont_pass1"),
"dont_pass1",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.dont_pass1=a;a=new CBetTableButton(252,259,s_oSpriteLibrary.getSprite("hit_area_dont_pass2"),"dont_pass2",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,
this));c.dont_pass2=a;a=new CBetTableButton(321,195,s_oSpriteLibrary.getSprite("hit_area_dont_come"),"dont_come",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.dont_come=a;a=new CBetTableButton(536,327,s_oSpriteLibrary.getSprite("hit_area_come"),"come",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,
this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.come=a;a=new CBetTableButton(536,433,s_oSpriteLibrary.getSprite("hit_area_field"),"field",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.field=a;a=new CBetTableButton(304,480,s_oSpriteLibrary.getSprite("hit_area_big_8"),"big_8",b);a.addEventListener(ON_MOUSE_DOWN,
this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.big_8=a;a=new CBetTableButton(274,455,s_oSpriteLibrary.getSprite("hit_area_big_6"),"big_6",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.big_6=a;for(var e=[{value:4,x:408,y:142},{value:5,
x:494,y:142},{value:6,x:580,y:142},{value:8,x:666,y:142},{value:9,x:752,y:142},{value:10,x:838,y:142}],d=0;6>d;d++)a=new CBetTableButton(e[d].x,e[d].y,s_oSpriteLibrary.getSprite("hit_area_lay_bet"),"lay_bet"+e[d].value,b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this)),c["lay_bet"+e[d].value]=a,a=new CBetTableButton(e[d].x,e[d].y+20,s_oSpriteLibrary.getSprite("hit_area_lose_bet"),
"lose_bet"+e[d].value,b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this)),c["lose_bet"+e[d].value]=a,a=new CBetTableButton(e[d].x,e[d].y+69,s_oSpriteLibrary.getSprite("hit_area_number"),"number"+e[d].value,b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,
this._onBetNumberOut,this)),c["number"+e[d].value]=a,a=new CBetTableButton(e[d].x,e[d].y+116,s_oSpriteLibrary.getSprite("hit_area_lose_bet"),"win_bet"+e[d].value,b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this)),c["win_bet"+e[d].value]=a;for(var e=[{x:820,y:299},{x:820,y:337},{x:820,y:374},{x:820,y:410},{x:820,y:447},{x:820,y:484},{x:820,y:521}],d=[{x:855,
y:308},{x:855,y:342},{x:855,y:376},{x:855,y:410},{x:855,y:445},{x:855,y:479},{x:855,y:514}],f=0;7>f;f++)a=new CBetTableButton(e[f].x,e[f].y+116,s_oSpriteLibrary.getSprite("hit_area_circle"),"any11_7",b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this)),c["any11_"+f]=a,a=new CBetTableButton(d[f].x,d[f].y+116,s_oSpriteLibrary.getSprite("hit_area_circle"),"any_craps_7",
b),a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this),!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this)),c["any_craps_"+f]=a;a=new CBetTableButton(1031,355,s_oSpriteLibrary.getSprite("hit_area_seven"),"seven_bet",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));
c.seven_bet=a;a=new CBetTableButton(954,401,s_oSpriteLibrary.getSprite("hit_area_proposition1"),"hardway6",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.hardway6=a;a=new CBetTableButton(1109,401,s_oSpriteLibrary.getSprite("hit_area_proposition1"),"hardway10",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,
this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.hardway10=a;a=new CBetTableButton(954,460,s_oSpriteLibrary.getSprite("hit_area_proposition1"),"hardway8",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.hardway8=a;a=new CBetTableButton(1109,460,s_oSpriteLibrary.getSprite("hit_area_proposition1"),"hardway4",b);
a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.hardway4=a;a=new CBetTableButton(928,521,s_oSpriteLibrary.getSprite("hit_area_proposition2"),"horn3",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.horn3=
a;a=new CBetTableButton(1032,521,s_oSpriteLibrary.getSprite("hit_area_proposition2"),"horn2",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.horn2=a;a=new CBetTableButton(1136,521,s_oSpriteLibrary.getSprite("hit_area_proposition2"),"horn12",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,
this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.horn12=a;a=new CBetTableButton(1032,581,s_oSpriteLibrary.getSprite("hit_area_any11"),"any11_7",b);a.addEventListener(ON_MOUSE_DOWN,this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.any11_7=a;a=new CBetTableButton(1032,628,s_oSpriteLibrary.getSprite("hit_area_any_craps"),"any_craps_7",b);a.addEventListener(ON_MOUSE_DOWN,
this._onBetPress,this);!1===s_bMobile&&(a.addEventListener(ON_MOUSE_OVER,this._onBetNumberOver,this),a.addEventListener(ON_MOUSE_OUT,this._onBetNumberOut,this));c.any_craps_7=a};this.setState=function(a){switch(a){case STATE_GAME_WAITING_FOR_BET:for(var b in c)"come"===b||"dont_come"===b?c[b].setVisible(!1):c[b].setVisible(!0);break;case STATE_GAME_COME_POINT:for(b in c)"pass_line"===b||"dont_pass1"===b||"dont_pass2"===b?c[b].setVisible(!1):c[b].setVisible(!0)}};this.unload=function(){for(var a=0;a<
b.getNumChildren();a++){var c=b.getChildAt(a);c instanceof CBetTableButton&&c.unload()}};this.addEventListener=function(a,b,c){e[a]=b;g[a]=c};this._onBetPress=function(a){null!==a.numbers&&e[ON_SHOW_BET_ON_TABLE]&&e[ON_SHOW_BET_ON_TABLE].call(g[ON_SHOW_BET_ON_TABLE],a,!1)};this._onBetNumberOver=function(a){null!==a.numbers&&e[ON_SHOW_ENLIGHT]&&e[ON_SHOW_ENLIGHT].call(g[ON_SHOW_ENLIGHT],a)};this._onBetNumberOut=function(a){null!==a.numbers&&e[ON_HIDE_ENLIGHT]&&e[ON_HIDE_ENLIGHT].call(g[ON_HIDE_ENLIGHT],
a)};this.enlight=function(a){if(-1!==a.indexOf("any11_"))for(a=0;8>a;a++)d["any11_"+a].show();else if(-1!==a.indexOf("any_craps_"))for(a=0;8>a;a++)d["any_craps_"+a].show();else d[a].show()};this.enlightOff=function(a){if(-1!==a.indexOf("any11_"))for(a=0;8>a;a++)d["any11_"+a].hide();else if(-1!==a.indexOf("any_craps_"))for(a=0;8>a;a++)d["any_craps_"+a].hide();else d[a].hide()};this.getEnlightX=function(a){return d["oEnlight_"+a].getX()};this.getEnlightY=function(a){return d["oEnlight_"+a].getY()};
this.getContainer=function(){return b};this.getX=function(){return b.x};this.getY=function(){return b.x};this._init()}function CEnlight(c,d,b,e){var g;this._init=function(a,b,c,f){g=createBitmap(c);g.x=a;g.y=b;g.visible=!1;f.addChild(g)};this.show=function(){g.visible=!0};this.hide=function(){g.visible=!1};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(c,d,b,e)}
function CFiche(c,d,b,e,g){var a,k,l,f,q;this._init=function(b,c,e,d,g){q=d;d=s_oSpriteLibrary.getSprite("fiche_"+e);f=createBitmap(d);f.x=b;f.y=c;f.regX=d.width/2;f.regY=d.height/2;g?(f.scaleX=g,f.scaleY=g):(f.scaleX=.6,f.scaleY=.6);a=e;q.addChild(f)};this.setEndPoint=function(a,b){k=new createjs.Point(f.x,f.y);l=new createjs.Point(a,b)};this.updatePos=function(a){var b=new createjs.Point,b=s_oTweenController.tweenVectors(k,l,a,b);f.x=b.x;f.y=b.y};this.getSprite=function(){return f};this.getValue=
function(){return a};this.getStartingPos=function(){return k};this._init(c,d,b,e,g)}
function CDicesAnim(c,d){var b,e,g,a,k,l,f,q,h,m,r;this._init=function(a,b){g=e=0;m=new createjs.Container;m.visible=!1;m.x=a;m.y=b;s_oStage.addChild(m);var c=(new createjs.Graphics).beginFill("rgba(0,0,0,0.6)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT),c=new createjs.Shape(c);c.x=-a;c.y=-b;m.addChild(c);c=createBitmap(s_oSpriteLibrary.getSprite("dices_screen_bg"));m.addChild(c);k=[];for(c=0;c<NUM_DICE_ROLLING_FRAMES;c++){var d=createBitmap(s_oSpriteLibrary.getSprite("launch_dices_"+c));d.x=162;d.y=
150;d.visible=!1;m.addChild(d);k.push(d)}q=k[0];q.visible=!0;c={images:[s_oSpriteLibrary.getSprite("dice_a")],frames:{width:80,height:34},animations:{anim_1:[0,9,"stop_anim_1"],anim_2:[10,19,"stop_anim_2"],anim_3:[20,29,"stop_anim_3"],anim_4:[30,39,"stop_anim_4"],anim_5:[40,49,"stop_anim_5"],anim_6:[50,59,"stop_anim_6"],stop_anim_1:9,stop_anim_2:19,stop_anim_3:29,stop_anim_4:39,stop_anim_5:49,stop_anim_6:59}};c=new createjs.SpriteSheet(c);l=createSprite(c,"anim_1",80,34);l.stop();l.visible=!1;l.x=
332;l.y=206;m.addChild(l);c={images:[s_oSpriteLibrary.getSprite("dice_b")],frames:{width:102,height:65},animations:{anim_1:[0,14,"stop_anim_1"],anim_2:[15,29,"stop_anim_2"],anim_3:[30,44,"stop_anim_3"],anim_4:[45,59,"stop_anim_4"],anim_5:[60,74,"stop_anim_5"],anim_6:[75,89,"stop_anim_6"],stop_anim_1:14,stop_anim_2:29,stop_anim_3:44,stop_anim_4:59,stop_anim_5:74,stop_anim_6:89}};c=new createjs.SpriteSheet(c);f=createSprite(c,"anim_1",102,65);f.stop();f.visible=!1;f.x=239;f.y=240;m.addChild(f);f.addEventListener("animationend",
r._onDiceBAnimEnded);h=new CDicesTopDownView(584,20,m)};this.hide=function(){h.hide();m.visible=!1;l.visible=!1;f.visible=!1;for(var a=0;a<k.length;a++)k[a].visible=!1;s_oGame.dicesAnimEnded()};this.startRolling=function(c){a=c;this.playToFrame(0);b=m.visible=!0;m.visible=!0;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("dice_rolling")};this.setShowNumberInfo=function(){h.setDiceResult(a[0],a[1])};this.playToFrame=function(a){q.visible=!1;e=a;k[e].visible=!0;q=k[e]};this.nextFrame=
function(){q.visible=!1;e++;k[e].visible=!0;q=k[e]};this._setAnimForDiceResult=function(){k[e].visible=!1;l.visible=!0;f.visible=!0;l.gotoAndPlay("anim_"+a[0]);f.gotoAndPlay("anim_"+a[1])};this._onDiceBAnimEnded=function(a){-1!==a.currentTarget.currentAnimation.indexOf("stop_anim")&&(r.setShowNumberInfo(),setTimeout(function(){r.hide()},TIME_SHOW_DICES_RESULT))};this.isVisible=function(){return m.visible};this.update=function(){!1!==b&&(g++,1===g&&(g=0,e===NUM_DICE_ROLLING_FRAMES-1?(b=!1,this._setAnimForDiceResult()):
this.nextFrame()))};r=this;this._init(c,d)}
function CGameOver(){var c,d,b,e,g;this._init=function(){g=new createjs.Container;s_oStage.addChild(g);var a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));g.addChild(a);c=new createjs.Text(TEXT_NO_MONEY,"36px "+FONT1,"#fff");c.textAlign="center";c.lineWidth=500;c.x=CANVAS_WIDTH/2;c.y=240;g.addChild(c);d=new createjs.Text(TEXT_RECHARGE_MSG,"20px "+FONT1,"#fff");d.textAlign="center";d.lineWidth=500;d.x=CANVAS_WIDTH/2;d.y=400;g.addChild(d);b=new CTextButton(CANVAS_WIDTH/2+170,510,s_oSpriteLibrary.getSprite("but_bg"),
TEXT_RECHARGE,FONT1,"#fff",18,!1);b.addEventListener(ON_MOUSE_UP,this._onRecharge,this);g.addChild(b.getSprite());e=new CTextButton(CANVAS_WIDTH/2-170,510,s_oSpriteLibrary.getSprite("but_bg"),TEXT_EXIT,FONT1,"#fff",18,!1);e.addEventListener(ON_MOUSE_UP,this._onExit,this);g.addChild(e.getSprite());this.hide()};this.unload=function(){b.unload();e.unload()};this.show=function(){g.visible=!0};this.hide=function(){g.visible=!1};this._onRecharge=function(){s_oGame.onRecharge()};this._onExit=function(){s_oGame.onExit(!0)};
this._init()}
function CCreditsPanel(){var c,d,b,e,g,a,k;this._init=function(){k=new createjs.Container;s_oStage.addChild(k);var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(l);l=s_oSpriteLibrary.getSprite("msg_box");d=createBitmap(l);d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.regX=l.width/2;d.regY=l.height/2;k.addChild(d);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;g.on("click",this._onLogoButRelease);k.addChild(g);l=s_oSpriteLibrary.getSprite("but_exit");
c=CANVAS_WIDTH/2+234;b=new CGfxButton(c,254,l,k);b.addEventListener(ON_MOUSE_UP,this.unload,this);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,"26px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=300;e.textAlign="center";k.addChild(e);var l=s_oSpriteLibrary.getSprite("logo_credits"),f=createBitmap(l);f.regX=l.width/2;f.regY=l.height/2;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;k.addChild(f);a=new createjs.Text(TEXT_LINK,"30px Arial","#ffffff");a.x=CANVAS_WIDTH/2;a.y=444;a.textAlign="center";k.addChild(a)};this.unload=
function(){g.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(k)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CRollingTextController(c,d,b,e,g,a,k){var l,f,q,h,m,r,v,t,p,w,n,u=[],x,y;this._init=function(a,b,c,f,d,e,g){w=[];n=[];m=d;this.setUpdateInfo(c,f);t=e;p=g;x=a;y=b};this.unload=function(){clearInterval(v)};this.setUpdateInfo=function(a,b){q=parseFloat(a);h=q+b;l=0;f=Math.round(m/FPS);r=0;var c=this;v=setInterval(function(){c.update()},FPS_TIME)};this.addEventListener=function(a,b,c){w[a]=b;n[a]=c};this.addRollingListener=function(a,b,c){w[ON_CONTROLLER_ROLL]=a;n[ON_CONTROLLER_ROLL]=b;u=[];
for(a=0;a<c.length;a++)u[a]={step:c[a],flag:!1}};this.increaseValue=function(a){r=a};this.getTarget=function(){return x};this.update=function(){l++;if(l>f)l=0,x.text=h.toFixed(2)+p,null!==y&&(y.text=h.toFixed(2)+p),clearInterval(v),null!==w[ON_CONTROLLER_END]&&void 0!==w[ON_CONTROLLER_END]&&w[ON_CONTROLLER_END].call(n[ON_CONTROLLER_END],this),0<r?this.setUpdateInfo(r):null!==w[ON_CONTROLLER_REMOVE]&&void 0!==w[ON_CONTROLLER_REMOVE]&&w[ON_CONTROLLER_REMOVE].call(n[ON_CONTROLLER_REMOVE],this);else{var a;
switch(t){case EASE_BACKIN:a=s_oTweenController.easeInBack(l,0,1,f);break;case EASE_BACKOUT:a=s_oTweenController.easeOutBack(l,0,1,f);break;case EASE_CUBIC_IN:a=s_oTweenController.easeInCubic(l,0,1,f);break;case EASE_CUBIC_OUT:a=s_oTweenController.easeOutCubic(l,0,1,f);break;case EASE_ELASTIC_OUT:a=s_oTweenController.easeOutElastic(l,0,1,f);break;case EASE_LINEAR:a=s_oTweenController.easeLinear(l,0,1,f);break;case EASE_QUART_BACKIN:a=s_oTweenController.easeBackInQuart(l,0,1,f);break;default:a=s_oTweenController.easeLinear(l,
0,1,f)}a=s_oTweenController.tweenValue(q,h,a);for(var b=0;b<u.length;b++)a>u[b].step&&!u[b].flag&&(u[b].flag=!0,null!==w[ON_CONTROLLER_ROLL]&&w[ON_CONTROLLER_ROLL].call(n[ON_CONTROLLER_ROLL],b));x.text=a.toFixed(2)+p;null!==y&&(y.text=a.toFixed(2)+p)}};this._init(c,d,b,e,g,a,k)}
function CPuck(c,d,b){var e,g,a;this._init=function(){e=c;var b=s_oSpriteLibrary.getSprite("puck"),l=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{on:[0],off:[1]}});g=createSprite(l,"off",b.width/2/2,b.height/2,b.width/2,b.height);g.x=c;g.y=d;a.addChild(g)};this.switchOn=function(a){createjs.Tween.get(g).to({x:a},1E3,createjs.Ease.cubicOut).call(function(){g.gotoAndStop("on")})};this.switchOff=function(){createjs.Tween.get(g).to({x:e},
1E3,createjs.Ease.cubicOut).call(function(){g.gotoAndStop("off")})};a=b;this._init(c,d)}
function CDicesTopDownView(c,d,b){var e,g,a,k,l;this._init=function(b,c){k=new createjs.Container;k.x=b;k.y=c;k.visible=!1;l.addChild(k);var d=createBitmap(s_oSpriteLibrary.getSprite("dices_box"));k.addChild(d);var d=s_oSpriteLibrary.getSprite("dice_topdown1"),m={images:[d],frames:{width:d.width/6,height:d.height,regX:d.width/6/2,regY:d.height/2},animations:{dice_1:[0],dice_2:[1],dice_3:[2],dice_4:[3],dice_5:[4],dice_6:[5]}},m=new createjs.SpriteSheet(m);g=createSprite(m,"dice_1",d.width/6/2,d.height/
2,d.width/6,d.height);g.x=d.width/6/2+10;g.y=d.height/2;k.addChild(g);d=s_oSpriteLibrary.getSprite("dice_topdown2");m={images:[d],frames:{width:d.width/6,height:d.height,regX:d.width/6/2,regY:d.height/2},animations:{dice_1:[0],dice_2:[1],dice_3:[2],dice_4:[3],dice_5:[4],dice_6:[5]}};m=new createjs.SpriteSheet(m);a=createSprite(m,"dice_1",d.width/6/2,d.height/2,d.width/6,d.height);a.x=d.width/6/2+d.width/6+20;a.y=d.height/2;k.addChild(a);e=new createjs.Text(TEXT_COME_OUT+" ","20px "+FONT1,"#fff");
e.textAlign="center";e.x=d.width/6+15;e.y=d.height+8;k.addChild(e)};this.setDiceResult=function(b,c){g.gotoAndStop("dice_"+b);a.gotoAndStop("dice_"+c);e.text=TEXT_COME_OUT+" "+(b+c);k.alpha=0;k.visible=!0;createjs.Tween.get(k).to({alpha:1},400)};this.hide=function(){k.visible=!1};l=b;this._init(c,d)}
function CAreYouSurePanel(c){var d,b,e,g,a,k;this._init=function(){a=new createjs.Container;a.visible=!1;k.addChild(a);var c=s_oSpriteLibrary.getSprite("msg_box");g=createBitmap(c);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2;g.regX=.5*c.width;g.regY=.5*c.height;a.addChild(g);g.on("click",function(){});d=new createjs.Text(TEXT_ARE_SURE,"60px "+FONT1,"#fff");d.x=CANVAS_WIDTH/2;d.y=.5*CANVAS_HEIGHT-40;d.textAlign="center";d.textBaseline="middle";a.addChild(d);b=new CGfxButton(CANVAS_WIDTH/2+186,d.y+140,s_oSpriteLibrary.getSprite("but_yes"),
a);b.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-186,d.y+140,s_oSpriteLibrary.getSprite("but_not"),a);e.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this.show=function(){a.visible=!0};this.unload=function(){e.unload();b.unload();g.off("click",function(){})};this._onButYes=function(){this.unload();playSound("click",1,0);s_oGame.onConfirmExit()};this._onButNo=function(){playSound("click",1,0);a.visible=!1};k=c;this._init()}
function CScoreText(c,d,b){var e;this._init=function(b,a,c){e=new createjs.Text("+"+b," 30px "+FONT1,"#ffffff");e.textAlign="center";e.x=a;e.y=c-10;e.alpha=0;e.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:1},500,createjs.Ease.quadIn).call(function(){createjs.Tween.get(e).wait(1E3).to({alpha:0},500)});this.moveUp()};this.moveUp=function(){var b=e.y-40,a=this;createjs.Tween.get(e).to({y:b},2E3,createjs.Ease.sineIn).call(function(){a.unload()})};this.unload=
function(){s_oStage.removeChild(e)};this._init(c,d,b)};
